### ISSUE TITLE
Support properties

### ISSUE THREAD

**Issue by zeenix** [antoyo/dbus-macros-rs#14]
Macros aren't very useful if we don't support D-Bus properties, some APIs are very props-based.

**Comment by zeenix** [comment]
I was looking at adding properties support to dbus-macros and saw these 'variables' support in server macros. What's that about and has it anything to do with properties? @antoyo ?

My idea for properties currently is:

```
 dbus_class!("com.dbus.test", class Hello (variable: i32) {
+    prop1: i32
+    prop2: String
+
     fn hello(&this) -> String {
         "Hello!"
     }
```
Better ideas? Don't say proc_macros. :)

**Comment by antoyo** [comment]
No, these variables are used to keep a state in the server.
Look at [this in the server example](https://github.com/antoyo/dbus-macros-rs/blob/master/examples/server.rs#L60).

I believe you need to look at [`properties`](https://docs.rs/dbus/0.5.2/dbus/tree/struct.Factory.html#method.property).

**Comment by zeenix** [comment]
@antoyo Thanks. I'm just wondering what would be a nice way to consolidate these variables but I guess we can keep them separate.

**Comment by zeenix** [comment]
This crate is no longer maintained or developed and is dropped in favor of [zbus](https://crates.io/crates/zbus) that provides much better API and has macros.

**Comment by zeenix** [comment]
I made a typo in my previous comment. The correct URL is https://crates.io/crates/zbus
