### ISSUE TITLE
Examples with dictionaries

### ISSUE THREAD

**Issue by spease** [antoyo/dbus-macros-rs#24]
Would be great if the readme showed an example with dictionaries. Trying to figure that out now.

**Comment by zeenix** [comment]
This crate is no longer maintained or developed and is dropped in favor of [zbus](https://crates.io/crates/zbus) that provides much better API and has macros.

**Comment by zeenix** [comment]
I made a typo in my previous comment. The correct URL is https://crates.io/crates/zbus
