### ISSUE TITLE
Automatic CamelCasing of methods

### ISSUE THREAD

**Issue by zeenix** [antoyo/dbus-macros-rs#6]
The DBus convention is to always CamelCase method names but Rust convention is small letter + underscores (you actually get even a warning from rustc about it). Vala has exactly the same so it automatically converts the case for you and I think we should do the same in here.

**Comment by antoyo** [comment]
I don't think we can do that with `macro_rules`.
It will be possible when this crate will switch to use attributes (compiler plugin).
Switching to a compiler plugin will also dramatically reduce the redundancy in the code.

**Comment by zeenix** [comment]
Hmm.. yeah it not possible to do it in an efficient way i guess but now, can we maybe do it at runtime cost?

**Comment by antoyo** [comment]
Oh, I misunderstood what you said: I thought you wanted the Rust method names to be converted to camel case, but you only want the dbus method names to be converted, right?
If that is the case, yes, we can convert them at runtime.

> small letter + underscores

By the way, it is called [snake case](https://en.wikipedia.org/wiki/Snake_case) ;) .

Every call to `stringify!($func_name)` can be changed to `camel_to_snake_case(stringify!($func_name))`.
Actually, there is already a [crate](https://crates.io/crates/case) to do so.

**Comment by zeenix** [comment]
> Oh, I misunderstood what you said: I thought you wanted the Rust method names to be converted to camel case, but you only want the dbus method names to be converted, right?

Yeah, that's what I meant. :) Don't think it makes sense to change names in Rust.

> By the way, it is called snake case ;) 

Thanks. I keep forgetting. :)

> Every call to stringify!($func_name) can be changed to camel_to_snake_case(stringify!($func_name)).
Actually, there is already a crate to do so.

Cool. :)
